spring:
  profiles:
    include: google

---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 249090985890-o007e6qc2h6crjtli3joigluntqm0p1l.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile