spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/springboot?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    driverClassName: org.mariadb.jdbc.Driver
    password: dlrpehlsp105!
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

  security:
    oauth2.client:
      registration:
        google:
          clientId: 414960384621-98vliumf1q9u2qqgsfctdcl52lpcocsj.apps.googleusercontent.com
          clientSecret: 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
          scope:
            - email
            - profile
        naver:
          clientId: 61No1qNDaGEXDwKNQ4Th
          clientSecret: hPgLeg1uCb
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: http://localhost:8080/login/ouath2/code/naver
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: a6793fe9736ab7eead17ba1149daab8f
          clientSecret: E4kOwneDlYLOSMeviE0OD1yUkEBHOjUZ
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: http://localhost:8080/login/oauth2/code/kakao
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao

      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect