spring:
  datasource:
    username: admin
    url: jdbc:mariadb://jiguhero-webservice-db.ccqinedppsob.ap-northeast-2.rds.amazonaws.com:3306/jiguhero_webservice_db?serverTimezone=Asia/Seoul
    driverClassName: org.mariadb.jdbc.Driver
    password: dlrpehlsp105!
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: a6793fe9736ab7eead17ba1149daab8f
            client-secret: E4kOwneDlYLOSMeviE0OD1yUkEBHOjUZ
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: profile_nickname, profile_image, account_email
          naver:
            client-id: 61No1qNDaGEXDwKNQ4Th
            client-secret: QLL0txFJOr
            redirect-uri:  http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 414960384621-98vliumf1q9u2qqgsfctdcl52lpcocsj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response