spring:
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3307/springboot
    driverClassName: org.mariadb.jdbc.Driver
    password: dlrpehlsp105!
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 249090985890-o007e6qc2h6crjtli3joigluntqm0p1l.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
app:
  auth:
    tokenSecret: VyLON8FXX6pnVNqgOxKW01cCSEAxpodxasdfrgaASD3253qaASDF134142354AR234322AREGASADG235QX6pnVNqgOxKW01cCSEAxpodxasdfrgaASD3253qaASDF134142354AR234322AREGASADG235Q
    # ex) tokenSecret: 926D96C90030DD58429D2751AC1BDBBC124123253qaASDF134142354AR234322AREGASADG235Q
    tokenExpirationMsec: 86400000000
    # ex) tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect